Repository Homebrew/homebrew-cask-fonts, pull requests merged in 2021-02, with the labels that each got.

#3605 Add font KanjiStrokeOrders
  Casks/font-kanjistrokeorders.rb
Labels: awaiting user reply

#3631 CONTRIBUTING.md: new rules for including casks
  CONTRIBUTING.md
Labels: documentation

#3630 Add Apple system fonts
  Casks/font-new-york.rb
  Casks/font-sf-compact.rb
  Casks/font-sf-mono.rb
  Casks/font-sf-pro.rb
Labels: awaiting maintainer feedback
